#!/bin/bash

set -e

install_link() {
    if [[ $# -ne 2 ]]; then
        echo "invalid argument count: $#"
        return 1
    fi

    if [[ -e $2 && ! -L $2 ]]; then
        echo "destination file $2 exists but isn't a link; aborting to prevent overwriting"
        return 1
    fi

    ln -sfv -T $1 $2
}

install_link $PWD/bashrc ~/.bashrc
install_link $PWD/kitty ~/.config/kitty
install_link $PWD/nvim ~/.config/nvim
